### ISSUE TITLE
Settings does not exist

### ISSUE THREAD

**Issue by AVATOR** [lexxpavlov/LexxpavlovSettingsBundle#4]
Hi.
I try to get data by "name" which doesn't exist and get error
`Error: Call to a member function getValue() on null`

Please, return "" if settings don't exist.

**Comment by lexxpavlov** [comment]
I don't think that settings may be dynamic. If you need with concrete setting, than create it. I supposed
 that settings will use as static rarely changed values.

How do you plan to use settings so that it can be null?

**Comment by AVATOR** [comment]
I work with Magento and it return "" if setting can not find. 
Example:
I create setting "heder_phone". Web-site will stop work if manager accidentally deleted a setting.

**Comment by lexxpavlov** [comment]
It's really bug. I will fix soon.

You can configure SonataAdminBundle that manager can't delete setting (superadmin can everything):
```yaml
# app/config/config.yml
sonata_admin:
    security:
        handler: sonata.admin.security.handler.role

# app/config/security.yml
security:
    role_hierarchy:
        ROLE_SONATA_MANAGER:
            - ROLE_APP_ADMIN_ARTICLE_ALL
            - ROLE_LEXXPAVLOV_SONATA_ADMIN_SETTINGS_LIST
            - ROLE_LEXXPAVLOV_SONATA_ADMIN_SETTINGS_EDIT
            - ROLE_LEXXPAVLOV_SONATA_ADMIN_SETTINGS_SHOW
#            - ROLE_APP_ADMIN_USER_ALL

        ROLE_ADMIN:       [ ROLE_USER, ROLE_SONATA_ADMIN ]
        ROLE_MANAGER:     [ ROLE_ADMIN, ROLE_SONATA_MANAGER ]
        ROLE_SUPER_ADMIN: [ ROLE_MANAGER, ROLE_ALLOWED_TO_SWITCH ]
```
See [security docs](https://sonata-project.org/bundles/admin/3-x/doc/reference/security.html).
